### ISSUE TITLE
Rocklife music

### ISSUE THREAD

**Issue by eserna27** [robzolkos/turbonativedirectory#17]
Hi i work in app call "Rocklife" and we use TurboNative to build the apps here are the links:
https://play.google.com/store/apps/details?id=com.rocklife.app
https://apps.apple.com/mx/app/rocklife/id1621826773

Nice work with this directory 🤘

**Comment by robzolkos** [comment]
Thanks @eserna27 Add in https://github.com/robzolkos/turbonativedirectory/pull/19
