### ISSUE TITLE
Add EnjoyKitchen App

### ISSUE THREAD

**Issue by fedegl** [robzolkos/turbonativedirectory#21]
Hello!

At Enjoy Kitchen we have a Turbo Native app on both Play and Apple stores.

Apple Store Link: https://apps.apple.com/mx/app/enjoy-kitchen/id6443742018
Play Store Link: https://play.google.com/store/apps/details?id=mx.enjoykitchen.shop

Thanks!

**Comment by robzolkos** [comment]
Thanks @fedegl  Added in https://github.com/robzolkos/turbonativedirectory/commit/c36ee5d03638a268c06e5851bef422e1b0c9afd6

Appreciate it.

**Comment by fedegl** [comment]
Thanks to you! @robzolkos 😄
