### ISSUE TITLE
Ploi - Plant Journal

### ISSUE THREAD

**Issue by devjah** [robzolkos/turbonativedirectory#25]
A plant journaling app built with Turbo Native :)

https://apps.apple.com/app/apple-store/id1624280409?pt=124998291&ct=tnd&mt=8

https://play.google.com/store/apps/details?id=com.devjah.plants

**Comment by robzolkos** [comment]
Added!

**Comment by devjah** [comment]
Thank you!
Apologies, I didn't realize that you can also add a web link in addition to mobile apps.
https://ploi.me/

**Comment by robzolkos** [comment]
> Thank you! Apologies, I didn't realize that you can also add a web link in addition to mobile apps. https://ploi.me/

Added!  Thanks
