### ISSUE TITLE
Add Wavclouds to Directory | Hotwire powered music app

### ISSUE THREAD

**Issue by enochtamulonis** [robzolkos/turbonativedirectory#36]
I want to add Wavclouds to the list. It is a music streaming and licensing platform built with Rails 7, Hotwire, Tailwind, Turbo Native
The code is public and open-source free to share and reuse it.

Web App
  Website link: https://www.wavclouds.com/
  Github link: https://github.com/enochtamulonis/beats

iOS App
  Apple store link: https://apps.apple.com/us/app/wavclouds/id6465136889
  Github link: https://github.com/enochtamulonis/wavclouds-ios-new

Android App
  Google Play store link: https://play.google.com/store/apps/details?id=com.wavclouds.mist
  Github link: https://github.com/enochtamulonis/wavclouds-android

This is the logo.
![wavclouds512x512 (1) (1)](https://github.com/robzolkos/turbonativedirectory/assets/63070125/17e81337-e100-4e75-bdea-3ef747ec6811)

**Comment by robzolkos** [comment]
Hey @enochtamulonis how are you mate!  Would you be able to create a PR for this please?  

The YAML file is all that needs to be updated https://github.com/robzolkos/turbonativedirectory/blob/main/config/app_directory.yml  and drop the image into app/assets/images/apps

**Comment by enochtamulonis** [comment]
Hey, I'm doing good! Awesome site you put together I love it! Really great to have examples of apps built with Turbo Native and Hotwire

**Comment by robzolkos** [comment]
Closed by https://github.com/robzolkos/turbonativedirectory/pull/37  Thanks!
