### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by work-leonid** [robzolkos/turbonativedirectory#58]
Hi, I had some time and thought the UI of the site could be improved
- add a site logo
- improve the UI of the card
- make the buttons bigger
- make the icons square, as this is the proportions used in all stores

https://github.com/robzolkos/turbonativedirectory/assets/8654430/05f3d4d4-7ff9-4b58-a5db-6f57069bcb62

I've made all the changes in the code, but I can't do a PR. If you're interested, I'd be happy to send you the code, please, tell me how 😂

**Comment by robzolkos** [comment]
Hey @work-leonid - this is amazing!  Thank you so much for taking the time.    I'd love to help you create a PR for this (let me know what the challenges are - if its your first one I'm happy to spend the time to show you (we can zoom).  Let me know how I can help get this in.

**Comment by work-leonid** [comment]
@robzolkos I think I did it! Check it out, please.
https://github.com/robzolkos/turbonativedirectory/pull/59

**Comment by robzolkos** [comment]
Closed in https://github.com/robzolkos/turbonativedirectory/pull/60  Thanks again @work-leonid ❤️
