### ISSUE TITLE
Add Malo - Bébé, Enfant, Parent

### ISSUE THREAD

**Issue by reaper** [robzolkos/turbonativedirectory#65]
iOS app: https://apps.apple.com/fr/app/malo-b%C3%A9b%C3%A9-enfant-parent/id1535908879
Android app: https://play.google.com/store/apps/details?id=com.kelindi.malo

**Comment by robzolkos** [comment]
Hey @reaper - are you able to open a PR with these details? Also is there a web application for these?

**Comment by reaper** [comment]
> Yeah of course @robzolkos, will do it

Done: https://github.com/robzolkos/turbonativedirectory/pull/66
