### ISSUE TITLE
SleepHQ Turbo Native iOS app

### ISSUE THREAD

**Issue by adampal** [robzolkos/turbonativedirectory#77]
Hey Rob, thanks for putting this together! I clicked the Add my app button and it took me here. Not sure if you need any more info than just the link to the App Store?  If so please let me know and I can update it.

Right now the SleepHQ app is only available on iOS.

https://apps.apple.com/au/app/sleephq/id6451459781

Thanks!

Adam

**Comment by robzolkos** [comment]
Hey @adampal - thanks!   Please have a look at some of the closed PR eg https://github.com/robzolkos/turbonativedirectory/pull/75 for how to update the YAML file and add the app image.  Then submit a PR and we'll get it merged asap.

**Comment by adampal** [comment]
thanks @robzolkos I've created PR #79 for this.
